package com.casciz.commerceos.domain.order.entity;

import com.casciz.commerceos.domain.checkout.valueobject.Address;
import com.casciz.commerceos.domain.order.valueobject.FulfilmentStatus;
import com.casciz.commerceos.domain.order.valueobject.OrderStatus;
import com.casciz.commerceos.domain.store.entity.Store;
import jakarta.persistence.*;
import lombok.*;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;

/**
 * Order aggregate root.
 *
 * <p>An Order is created from a completed {@link com.casciz.commerceos.domain.checkout.entity.Checkout}.
 * It owns its line items, timeline notes, and tracks fulfilment independently.
 */
@Entity
@Table(
    name = "orders",
    indexes = {
        @Index(name = "idx_orders_store_id",      columnList = "store_id"),
        @Index(name = "idx_orders_status",         columnList = "status"),
        @Index(name = "idx_orders_customer_email", columnList = "customer_email"),
        @Index(name = "idx_orders_order_number",   columnList = "order_number", unique = true),
        @Index(name = "idx_orders_created_at",     columnList = "created_at"),
        @Index(name = "idx_orders_checkout_id",    columnList = "checkout_id", unique = true)
    }
)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Order {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "store_id", nullable = false)
    private Store store;

    /** The checkout that originated this order. */
    @Column(name = "checkout_id", nullable = false, unique = true)
    private UUID checkoutId;

    /**
     * Human-readable sequential order number, e.g. "#1001".
     * Generated by the database sequence.
     */
    @Column(name = "order_number", nullable = false, unique = true, length = 20)
    private String orderNumber;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 30)
    @Builder.Default
    private OrderStatus status = OrderStatus.PENDING_PAYMENT;

    @Enumerated(EnumType.STRING)
    @Column(name = "fulfilment_status", nullable = false, length = 30)
    @Builder.Default
    private FulfilmentStatus fulfilmentStatus = FulfilmentStatus.UNFULFILLED;

    // ── Customer ──────────────────────────────────────────────────────────
    @Column(name = "customer_email", nullable = false, length = 255)
    private String customerEmail;

    @Column(name = "customer_first_name", length = 100)
    private String customerFirstName;

    @Column(name = "customer_last_name", length = 100)
    private String customerLastName;

    @Column(name = "customer_phone", length = 30)
    private String customerPhone;

    @Column(name = "customer_notes", columnDefinition = "TEXT")
    private String customerNotes;

    // ── Addresses ─────────────────────────────────────────────────────────
    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "fullName",    column = @Column(name = "shipping_full_name",    length = 120)),
        @AttributeOverride(name = "line1",       column = @Column(name = "shipping_line1",        length = 255)),
        @AttributeOverride(name = "line2",       column = @Column(name = "shipping_line2",        length = 255)),
        @AttributeOverride(name = "city",        column = @Column(name = "shipping_city",         length = 100)),
        @AttributeOverride(name = "state",       column = @Column(name = "shipping_state",        length = 100)),
        @AttributeOverride(name = "postalCode",  column = @Column(name = "shipping_postal_code",  length = 20)),
        @AttributeOverride(name = "countryCode", column = @Column(name = "shipping_country_code", length = 2)),
        @AttributeOverride(name = "phone",       column = @Column(name = "shipping_phone",        length = 30))
    })
    private Address shippingAddress;

    @Embedded
    @AttributeOverrides({
        @AttributeOverride(name = "fullName",    column = @Column(name = "billing_full_name",    length = 120)),
        @AttributeOverride(name = "line1",       column = @Column(name = "billing_line1",        length = 255)),
        @AttributeOverride(name = "line2",       column = @Column(name = "billing_line2",        length = 255)),
        @AttributeOverride(name = "city",        column = @Column(name = "billing_city",         length = 100)),
        @AttributeOverride(name = "state",       column = @Column(name = "billing_state",        length = 100)),
        @AttributeOverride(name = "postalCode",  column = @Column(name = "billing_postal_code",  length = 20)),
        @AttributeOverride(name = "countryCode", column = @Column(name = "billing_country_code", length = 2)),
        @AttributeOverride(name = "phone",       column = @Column(name = "billing_phone",        length = 30))
    })
    private Address billingAddress;

    // ── Pricing (snapshotted from checkout) ───────────────────────────────
    @Column(nullable = false, precision = 19, scale = 2)
    @Builder.Default
    private BigDecimal subtotal = BigDecimal.ZERO;

    @Column(name = "shipping_amount", precision = 19, scale = 2)
    @Builder.Default
    private BigDecimal shippingAmount = BigDecimal.ZERO;

    @Column(name = "tax_amount", precision = 19, scale = 2)
    @Builder.Default
    private BigDecimal taxAmount = BigDecimal.ZERO;

    @Column(name = "discount_amount", precision = 19, scale = 2)
    @Builder.Default
    private BigDecimal discountAmount = BigDecimal.ZERO;

    @Column(name = "total_amount", nullable = false, precision = 19, scale = 2)
    @Builder.Default
    private BigDecimal totalAmount = BigDecimal.ZERO;

    @Column(name = "refunded_amount", precision = 19, scale = 2)
    @Builder.Default
    private BigDecimal refundedAmount = BigDecimal.ZERO;

    @Column(nullable = false, length = 10)
    @Builder.Default
    private String currency = "USD";

    @Column(name = "coupon_code", length = 50)
    private String couponCode;

    // ── Payment reference ─────────────────────────────────────────────────
    @Column(name = "payment_provider", length = 30)
    private String paymentProvider;

    @Column(name = "payment_reference", length = 255)
    private String paymentReference;

    // ── Fulfilment / shipping ─────────────────────────────────────────────
    @Column(name = "tracking_number", length = 120)
    private String trackingNumber;

    @Column(name = "carrier_name", length = 80)
    private String carrierName;

    @Column(name = "tracking_url", length = 512)
    private String trackingUrl;

    @Column(name = "shipped_at")
    private Instant shippedAt;

    @Column(name = "delivered_at")
    private Instant deliveredAt;

    @Column(name = "estimated_delivery_at")
    private Instant estimatedDeliveryAt;

    // ── Timestamps ────────────────────────────────────────────────────────
    @Column(name = "created_at", nullable = false, updatable = false)
    @Builder.Default
    private Instant createdAt = Instant.now();

    @Column(name = "updated_at", nullable = false)
    @Builder.Default
    private Instant updatedAt = Instant.now();

    @Column(name = "cancelled_at")
    private Instant cancelledAt;

    @Column(name = "cancellation_reason", length = 255)
    private String cancellationReason;

    // ── Relations ─────────────────────────────────────────────────────────
    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true,
               fetch = FetchType.LAZY)
    @Builder.Default
    private List<OrderItem> items = new ArrayList<>();

    @OneToMany(mappedBy = "order", cascade = CascadeType.ALL, orphanRemoval = true,
               fetch = FetchType.LAZY)
    @OrderBy("createdAt ASC")
    @Builder.Default
    private List<OrderNote> notes = new ArrayList<>();

    @PreUpdate
    protected void onUpdate() { this.updatedAt = Instant.now(); }

    // ── Domain behaviour ──────────────────────────────────────────────────

    public void transitionTo(OrderStatus next) {
        if (!this.status.canTransitionTo(next)) {
            throw new IllegalStateException(
                    "Cannot transition order from " + this.status + " to " + next);
        }
        this.status = next;
    }

    public void cancel(String reason) {
        transitionTo(OrderStatus.CANCELLED);
        this.cancelledAt         = Instant.now();
        this.cancellationReason  = reason;
        this.fulfilmentStatus    = FulfilmentStatus.RETURNED;
    }

    public void markShipped(String trackingNumber, String carrierName,
                             String trackingUrl, Instant estimatedDelivery) {
        transitionTo(OrderStatus.SHIPPED);
        this.trackingNumber       = trackingNumber;
        this.carrierName          = carrierName;
        this.trackingUrl          = trackingUrl;
        this.shippedAt            = Instant.now();
        this.estimatedDeliveryAt  = estimatedDelivery;
        this.fulfilmentStatus     = FulfilmentStatus.SHIPPED;
    }

    public void markDelivered() {
        transitionTo(OrderStatus.DELIVERED);
        this.deliveredAt      = Instant.now();
        this.fulfilmentStatus = FulfilmentStatus.DELIVERED;
    }

    public boolean isOwnedByStore(UUID storeId) {
        return this.store != null && this.store.getId().equals(storeId);
    }

    public int getTotalItemCount() {
        return items.stream().mapToInt(OrderItem::getQuantity).sum();
    }

    public BigDecimal getRefundableAmount() {
        return totalAmount.subtract(refundedAmount);
    }

    public void addSystemNote(String body) {
        notes.add(OrderNote.builder()
                .order(this).body(body).system(true).visibleToCustomer(false).build());
    }
}
