package com.casciz.commerceos.domain.order.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.Instant;
import java.util.UUID;

/**
 * A timestamped note on an order — either a system event (status change, shipment)
 * or a manual note added by the store owner.
 */
@Entity
@Table(name = "order_notes",
    indexes = @Index(name = "idx_order_notes_order_id", columnList = "order_id"))
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class OrderNote {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(updatable = false, nullable = false)
    private UUID id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "order_id", nullable = false)
    private Order order;

    @Column(nullable = false, columnDefinition = "TEXT")
    private String body;

    /** True = generated by the system (status transition, shipment, etc.). */
    @Column(name = "is_system", nullable = false)
    @Builder.Default
    private boolean system = false;

    /** False = internal only (owner); True = also visible to the customer. */
    @Column(name = "visible_to_customer", nullable = false)
    @Builder.Default
    private boolean visibleToCustomer = false;

    @Column(name = "created_at", nullable = false, updatable = false)
    @Builder.Default
    private Instant createdAt = Instant.now();

    @Column(name = "author", length = 120)
    private String author;
}
